### ISSUE TITLE
Help with HS + RGB version

### ISSUE THREAD

**Issue by racsor17** [Envious-Data/Env-KB#2]
Hi, this is my first time building my own keyboard. Do I need to get and solder different materials that aren't in the list? Like RGB LEDs or anything to do the "hot-swap thing"? There is any building guide? To order the PCB in PCBWAY, I just have to drag the files and buy it? 
I just love this keyboard, you've done such a great job!

**Comment by racsor17** [comment]
LED's needsSMT solder??

**Comment by Envious-Data** [comment]
You'll have to download KiCad and generate gerbers, CPL and BOM for PCB way since what you might find in the gerber folder is for JLCPCB.

the LEDs can be hand soldered but they can be difficult if you get them from aliexpress, you are looking for SK6812 mini-e.

the hotswap sockets are typical kailh ones you can buy those from a number of stores.

diodes are 1n4148 Do-35s

**Comment by racsor17** [comment]
Thank you!
